"use client";
import local from "@next/font/local";
import "./globals.css";
import clsx from "clsx";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

// inculde the fonts in app by @next/font
const black = local({
  src: "./fonts/PingAR+LT-Black.otf",
  variable: "--font-ping-black",
});

const bold = local({
  src: "./fonts/PingAR+LT-Bold.otf",
  variable: "--font-ping-bold",
});

const medium = local({
  src: "./fonts/PingAR+LT-Medium.otf",
  variable: "--font-ping-medium",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={clsx(black.variable, bold.variable, medium.variable, "bg-gray-50")}
      >
        {children}
      </body>
    </html>
  );
}
